//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

pub use super::region::Entity as Region;
pub use super::weather_issued::Entity as WeatherIssued;
pub use super::weather_parameter::Entity as WeatherParameter;
pub use super::weather_prediction::Entity as WeatherPrediction;
