//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "weather_issued")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub timestamp: String,
    pub production_center: String,
    pub source: String,
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::weather_prediction::Entity")]
    WeatherPrediction,
}

impl Related<super::weather_prediction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WeatherPrediction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
